export const Symbols = {
    MoveSpeed: Symbol.for('MoveSpeed'),
    Gap: Symbol.for('Gap'),
    Gravity: Symbol.for('Gravity'),
    NewPipeGenerationPoint: Symbol.for('NewPipeGenerationPoint'),
    Canvas: Symbol.for('Canvas'),
    Context: Symbol.for('Context'),
    JumpHeight: Symbol.for('JumpHeight'),
    Bonus: Symbol.for('Bonus'),
    NorthPipeImage: Symbol.for('NorthPipeImage'),
    SouthPipeImage: Symbol.for('SouthPipeImage'),
    BackgroundImage: Symbol.for('BackgroundImage'),
    GroundImage: Symbol.for('GroundImage'),
    BirdImage: Symbol.for('BirdImage'),
};
